"""Test the deploy_simple_stack example."""

from __future__ import annotations

import sys
from pathlib import Path

import pytest
import yaml

TEST_DIR = Path(__file__).parent
EXAMPLES_DIR = TEST_DIR.parent.parent.parent / "examples"
sys.path.insert(0, str(EXAMPLES_DIR))
from deploy_simple_stack import main  # type: ignore # noqa: E402


def test_deploy_simple_stack_example(capsys: pytest.CaptureFixture) -> None:
    """Ensure the stack generated by deploy_simple_stack.py is the one expected."""
    with pytest.raises(SystemExit) as exit_info:
        main(["show"])

    captured = capsys.readouterr()
    expected_stack = yaml.safe_load(Path(TEST_DIR / "simple_stack.yml").read_text())
    assert yaml.safe_load(captured.out) == expected_stack
    assert exit_info.value.code == 0
    assert captured.err == ""
